### ISSUE TITLE
Добавить показ типа данных при наведении

### ISSUE THREAD

**Issue by alexbaumgertner** [htmlacademy/console-stub#4]
## Демо
![screen shot 2016-03-16 at 23 11 58](https://cloud.githubusercontent.com/assets/223620/13827255/861da120-ebcc-11e5-9b0e-5c8e355485b9.png)

## Возможное решение
```css
.console-container__code span:hover::after
{
  content: attr(class);
  position: relative;
  top: -15px;
  right: -15px;
  padding: 3px 6px;
  font-size: .9em;
  font-style: italic;
  border: 1px dashed;
  border-radius: 4px;
  opacity: .8;
}
```
